# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/gregcostello/Documents/dev/vulkan/BuffkinzEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/gregcostello/Documents/dev/vulkan/BuffkinzEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.29.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gregcostello/Documents/dev/vulkan/BuffkinzEngine/CMakeFiles /Users/gregcostello/Documents/dev/vulkan/BuffkinzEngine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gregcostello/Documents/dev/vulkan/BuffkinzEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BuffkinzRenderer

# Build rule for target.
BuffkinzRenderer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BuffkinzRenderer
.PHONY : BuffkinzRenderer

# fast build rule for target.
BuffkinzRenderer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/build
.PHONY : BuffkinzRenderer/fast

#=============================================================================
# Target rules for targets named shaders

# Build rule for target.
shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shaders
.PHONY : shaders

# fast build rule for target.
shaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/build
.PHONY : shaders/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f lib/glfw-3.4/CMakeFiles/uninstall.dir/build.make lib/glfw-3.4/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f lib/glfw-3.4/src/CMakeFiles/glfw.dir/build.make lib/glfw-3.4/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f lib/glfw-3.4/src/CMakeFiles/update_mappings.dir/build.make lib/glfw-3.4/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

src/engine_objects/Scene.o: src/engine_objects/Scene.cpp.o
.PHONY : src/engine_objects/Scene.o

# target to build an object file
src/engine_objects/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/engine_objects/Scene.cpp.o
.PHONY : src/engine_objects/Scene.cpp.o

src/engine_objects/Scene.i: src/engine_objects/Scene.cpp.i
.PHONY : src/engine_objects/Scene.i

# target to preprocess a source file
src/engine_objects/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/engine_objects/Scene.cpp.i
.PHONY : src/engine_objects/Scene.cpp.i

src/engine_objects/Scene.s: src/engine_objects/Scene.cpp.s
.PHONY : src/engine_objects/Scene.s

# target to generate assembly for a file
src/engine_objects/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/engine_objects/Scene.cpp.s
.PHONY : src/engine_objects/Scene.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/vulkan_objects/VulkanBufferManager.o: src/vulkan_objects/VulkanBufferManager.cpp.o
.PHONY : src/vulkan_objects/VulkanBufferManager.o

# target to build an object file
src/vulkan_objects/VulkanBufferManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanBufferManager.cpp.o
.PHONY : src/vulkan_objects/VulkanBufferManager.cpp.o

src/vulkan_objects/VulkanBufferManager.i: src/vulkan_objects/VulkanBufferManager.cpp.i
.PHONY : src/vulkan_objects/VulkanBufferManager.i

# target to preprocess a source file
src/vulkan_objects/VulkanBufferManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanBufferManager.cpp.i
.PHONY : src/vulkan_objects/VulkanBufferManager.cpp.i

src/vulkan_objects/VulkanBufferManager.s: src/vulkan_objects/VulkanBufferManager.cpp.s
.PHONY : src/vulkan_objects/VulkanBufferManager.s

# target to generate assembly for a file
src/vulkan_objects/VulkanBufferManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanBufferManager.cpp.s
.PHONY : src/vulkan_objects/VulkanBufferManager.cpp.s

src/vulkan_objects/VulkanCommandModule.o: src/vulkan_objects/VulkanCommandModule.cpp.o
.PHONY : src/vulkan_objects/VulkanCommandModule.o

# target to build an object file
src/vulkan_objects/VulkanCommandModule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanCommandModule.cpp.o
.PHONY : src/vulkan_objects/VulkanCommandModule.cpp.o

src/vulkan_objects/VulkanCommandModule.i: src/vulkan_objects/VulkanCommandModule.cpp.i
.PHONY : src/vulkan_objects/VulkanCommandModule.i

# target to preprocess a source file
src/vulkan_objects/VulkanCommandModule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanCommandModule.cpp.i
.PHONY : src/vulkan_objects/VulkanCommandModule.cpp.i

src/vulkan_objects/VulkanCommandModule.s: src/vulkan_objects/VulkanCommandModule.cpp.s
.PHONY : src/vulkan_objects/VulkanCommandModule.s

# target to generate assembly for a file
src/vulkan_objects/VulkanCommandModule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanCommandModule.cpp.s
.PHONY : src/vulkan_objects/VulkanCommandModule.cpp.s

src/vulkan_objects/VulkanDeviceManager.o: src/vulkan_objects/VulkanDeviceManager.cpp.o
.PHONY : src/vulkan_objects/VulkanDeviceManager.o

# target to build an object file
src/vulkan_objects/VulkanDeviceManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanDeviceManager.cpp.o
.PHONY : src/vulkan_objects/VulkanDeviceManager.cpp.o

src/vulkan_objects/VulkanDeviceManager.i: src/vulkan_objects/VulkanDeviceManager.cpp.i
.PHONY : src/vulkan_objects/VulkanDeviceManager.i

# target to preprocess a source file
src/vulkan_objects/VulkanDeviceManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanDeviceManager.cpp.i
.PHONY : src/vulkan_objects/VulkanDeviceManager.cpp.i

src/vulkan_objects/VulkanDeviceManager.s: src/vulkan_objects/VulkanDeviceManager.cpp.s
.PHONY : src/vulkan_objects/VulkanDeviceManager.s

# target to generate assembly for a file
src/vulkan_objects/VulkanDeviceManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanDeviceManager.cpp.s
.PHONY : src/vulkan_objects/VulkanDeviceManager.cpp.s

src/vulkan_objects/VulkanInstanceManager.o: src/vulkan_objects/VulkanInstanceManager.cpp.o
.PHONY : src/vulkan_objects/VulkanInstanceManager.o

# target to build an object file
src/vulkan_objects/VulkanInstanceManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanInstanceManager.cpp.o
.PHONY : src/vulkan_objects/VulkanInstanceManager.cpp.o

src/vulkan_objects/VulkanInstanceManager.i: src/vulkan_objects/VulkanInstanceManager.cpp.i
.PHONY : src/vulkan_objects/VulkanInstanceManager.i

# target to preprocess a source file
src/vulkan_objects/VulkanInstanceManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanInstanceManager.cpp.i
.PHONY : src/vulkan_objects/VulkanInstanceManager.cpp.i

src/vulkan_objects/VulkanInstanceManager.s: src/vulkan_objects/VulkanInstanceManager.cpp.s
.PHONY : src/vulkan_objects/VulkanInstanceManager.s

# target to generate assembly for a file
src/vulkan_objects/VulkanInstanceManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanInstanceManager.cpp.s
.PHONY : src/vulkan_objects/VulkanInstanceManager.cpp.s

src/vulkan_objects/VulkanPipelineManager.o: src/vulkan_objects/VulkanPipelineManager.cpp.o
.PHONY : src/vulkan_objects/VulkanPipelineManager.o

# target to build an object file
src/vulkan_objects/VulkanPipelineManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanPipelineManager.cpp.o
.PHONY : src/vulkan_objects/VulkanPipelineManager.cpp.o

src/vulkan_objects/VulkanPipelineManager.i: src/vulkan_objects/VulkanPipelineManager.cpp.i
.PHONY : src/vulkan_objects/VulkanPipelineManager.i

# target to preprocess a source file
src/vulkan_objects/VulkanPipelineManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanPipelineManager.cpp.i
.PHONY : src/vulkan_objects/VulkanPipelineManager.cpp.i

src/vulkan_objects/VulkanPipelineManager.s: src/vulkan_objects/VulkanPipelineManager.cpp.s
.PHONY : src/vulkan_objects/VulkanPipelineManager.s

# target to generate assembly for a file
src/vulkan_objects/VulkanPipelineManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanPipelineManager.cpp.s
.PHONY : src/vulkan_objects/VulkanPipelineManager.cpp.s

src/vulkan_objects/VulkanPoolManager.o: src/vulkan_objects/VulkanPoolManager.cpp.o
.PHONY : src/vulkan_objects/VulkanPoolManager.o

# target to build an object file
src/vulkan_objects/VulkanPoolManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanPoolManager.cpp.o
.PHONY : src/vulkan_objects/VulkanPoolManager.cpp.o

src/vulkan_objects/VulkanPoolManager.i: src/vulkan_objects/VulkanPoolManager.cpp.i
.PHONY : src/vulkan_objects/VulkanPoolManager.i

# target to preprocess a source file
src/vulkan_objects/VulkanPoolManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanPoolManager.cpp.i
.PHONY : src/vulkan_objects/VulkanPoolManager.cpp.i

src/vulkan_objects/VulkanPoolManager.s: src/vulkan_objects/VulkanPoolManager.cpp.s
.PHONY : src/vulkan_objects/VulkanPoolManager.s

# target to generate assembly for a file
src/vulkan_objects/VulkanPoolManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanPoolManager.cpp.s
.PHONY : src/vulkan_objects/VulkanPoolManager.cpp.s

src/vulkan_objects/VulkanSwapchainManager.o: src/vulkan_objects/VulkanSwapchainManager.cpp.o
.PHONY : src/vulkan_objects/VulkanSwapchainManager.o

# target to build an object file
src/vulkan_objects/VulkanSwapchainManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanSwapchainManager.cpp.o
.PHONY : src/vulkan_objects/VulkanSwapchainManager.cpp.o

src/vulkan_objects/VulkanSwapchainManager.i: src/vulkan_objects/VulkanSwapchainManager.cpp.i
.PHONY : src/vulkan_objects/VulkanSwapchainManager.i

# target to preprocess a source file
src/vulkan_objects/VulkanSwapchainManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanSwapchainManager.cpp.i
.PHONY : src/vulkan_objects/VulkanSwapchainManager.cpp.i

src/vulkan_objects/VulkanSwapchainManager.s: src/vulkan_objects/VulkanSwapchainManager.cpp.s
.PHONY : src/vulkan_objects/VulkanSwapchainManager.s

# target to generate assembly for a file
src/vulkan_objects/VulkanSwapchainManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanSwapchainManager.cpp.s
.PHONY : src/vulkan_objects/VulkanSwapchainManager.cpp.s

src/vulkan_objects/VulkanWindowManager.o: src/vulkan_objects/VulkanWindowManager.cpp.o
.PHONY : src/vulkan_objects/VulkanWindowManager.o

# target to build an object file
src/vulkan_objects/VulkanWindowManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanWindowManager.cpp.o
.PHONY : src/vulkan_objects/VulkanWindowManager.cpp.o

src/vulkan_objects/VulkanWindowManager.i: src/vulkan_objects/VulkanWindowManager.cpp.i
.PHONY : src/vulkan_objects/VulkanWindowManager.i

# target to preprocess a source file
src/vulkan_objects/VulkanWindowManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanWindowManager.cpp.i
.PHONY : src/vulkan_objects/VulkanWindowManager.cpp.i

src/vulkan_objects/VulkanWindowManager.s: src/vulkan_objects/VulkanWindowManager.cpp.s
.PHONY : src/vulkan_objects/VulkanWindowManager.s

# target to generate assembly for a file
src/vulkan_objects/VulkanWindowManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuffkinzRenderer.dir/build.make CMakeFiles/BuffkinzRenderer.dir/src/vulkan_objects/VulkanWindowManager.cpp.s
.PHONY : src/vulkan_objects/VulkanWindowManager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... shaders"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... BuffkinzRenderer"
	@echo "... glfw"
	@echo "... src/engine_objects/Scene.o"
	@echo "... src/engine_objects/Scene.i"
	@echo "... src/engine_objects/Scene.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/vulkan_objects/VulkanBufferManager.o"
	@echo "... src/vulkan_objects/VulkanBufferManager.i"
	@echo "... src/vulkan_objects/VulkanBufferManager.s"
	@echo "... src/vulkan_objects/VulkanCommandModule.o"
	@echo "... src/vulkan_objects/VulkanCommandModule.i"
	@echo "... src/vulkan_objects/VulkanCommandModule.s"
	@echo "... src/vulkan_objects/VulkanDeviceManager.o"
	@echo "... src/vulkan_objects/VulkanDeviceManager.i"
	@echo "... src/vulkan_objects/VulkanDeviceManager.s"
	@echo "... src/vulkan_objects/VulkanInstanceManager.o"
	@echo "... src/vulkan_objects/VulkanInstanceManager.i"
	@echo "... src/vulkan_objects/VulkanInstanceManager.s"
	@echo "... src/vulkan_objects/VulkanPipelineManager.o"
	@echo "... src/vulkan_objects/VulkanPipelineManager.i"
	@echo "... src/vulkan_objects/VulkanPipelineManager.s"
	@echo "... src/vulkan_objects/VulkanPoolManager.o"
	@echo "... src/vulkan_objects/VulkanPoolManager.i"
	@echo "... src/vulkan_objects/VulkanPoolManager.s"
	@echo "... src/vulkan_objects/VulkanSwapchainManager.o"
	@echo "... src/vulkan_objects/VulkanSwapchainManager.i"
	@echo "... src/vulkan_objects/VulkanSwapchainManager.s"
	@echo "... src/vulkan_objects/VulkanWindowManager.o"
	@echo "... src/vulkan_objects/VulkanWindowManager.i"
	@echo "... src/vulkan_objects/VulkanWindowManager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

